//! Generates SDUI primitive structs and the unified [`Component`] enum.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let primitives_path =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
            .join("sdui_primitives.json");
    let primitives_json = fs::read_to_string(&primitives_path).expect("read sdui_primitives.json");
    let primitives: Vec<PrimitiveSpec> =
        serde_json::from_str(&primitives_json).expect("parse sdui_primitives.json");

    let uses_temp_variant = primitives.iter().any(|primitive| {
        primitive
            .typed_fields
            .as_ref()
            .is_some_and(|fields| fields.values().any(|ty| ty == "TempVariant"))
    });

    let mut generated = String::from(
        "// @generated by build.rs — do not edit\n\
         use super::common::{Animation, Emphasis, SurfaceLevel, Tone, Visibility};\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    if uses_temp_variant {
        generated.push_str("use super::common::TempVariant;\n\n");
    }

    let mut enum_variants = String::new();
    let mut from_impls = String::new();

    for primitive in &primitives {
        let struct_name = &primitive.name;
        let serde_name = &primitive.serde_name;
        let has_children = primitive.has_children;
        let extra_fields = primitive.extra_fields.as_deref().unwrap_or(&[]);
        let typed_fields = primitive.typed_fields.as_ref();

        generated.push_str(&format!(
            "/// SDUI primitive `{serde_name}` — see PORTAKI_PLATFORM.md §5.\n"
        ));
        generated.push_str("#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]\n");
        generated.push_str(&format!("pub struct {struct_name} {{\n"));
        generated.push_str(common_field_defs());
        for field in extra_fields {
            generated.push_str(&format!(
                "    #[serde(skip_serializing_if = \"Option::is_none\")]\n\
                 pub {}: Option<serde_json::Value>,\n",
                field
            ));
        }
        if let Some(typed_fields) = typed_fields {
            for (field, ty) in typed_fields {
                generated.push_str(&format!(
                    "    #[serde(skip_serializing_if = \"Option::is_none\")]\n\
                     pub {}: Option<{ty}>,\n",
                    field
                ));
            }
        }
        if has_children {
            generated.push_str(
                "    #[serde(skip_serializing_if = \"Vec::is_empty\", default)]\n\
                 pub children: Vec<Component>,\n",
            );
        }
        generated.push_str("}\n\n");
        generated.push_str(&impl_builder(
            struct_name,
            has_children,
            extra_fields,
            typed_fields,
        ));

        enum_variants.push_str(&format!(
            "    #[serde(rename = \"{serde_name}\")]\n    {struct_name}({struct_name}),\n"
        ));
        from_impls.push_str(&impl_from_component(struct_name));
    }

    generated.push_str("/// Unified SDUI component tree node.\n");
    generated.push_str(
        "#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]\n\
         #[serde(tag = \"type\")]\n\
         pub enum Component {\n",
    );
    generated.push_str(&enum_variants);
    generated.push_str("}\n\n");
    generated.push_str(&from_impls);
    generated.push_str(
        "impl Default for Component {\n\
         fn default() -> Self {\n\
         Component::Stack(Stack::default())\n\
         }\n\
         }\n",
    );

    let dest = out_dir.join("generated_sdui.rs");
    fs::write(&dest, generated).expect("write generated_sdui.rs");
    println!("cargo:rerun-if-changed=sdui_primitives.json");
}

#[derive(serde::Deserialize)]
struct PrimitiveSpec {
    name: String,
    serde_name: String,
    has_children: bool,
    #[serde(default)]
    extra_fields: Option<Vec<String>>,
    #[serde(default)]
    typed_fields: Option<BTreeMap<String, String>>,
}

fn common_field_defs() -> &'static str {
    "    #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub id: Option<String>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub tone: Option<Tone>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub emphasis: Option<Emphasis>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub surface: Option<SurfaceLevel>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub animation: Option<Animation>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub visibility: Option<Visibility>,\n"
}

fn impl_builder(
    name: &str,
    has_children: bool,
    extra_fields: &[String],
    typed_fields: Option<&BTreeMap<String, String>>,
) -> String {
    let mut body = format!(
        "impl {name} {{\n\
         /// Creates an empty `{name}` primitive.\n\
         pub fn new() -> Self {{ Self::default() }}\n\
         pub fn id(mut self, value: impl Into<String>) -> Self {{ self.id = Some(value.into()); self }}\n\
         pub fn tone(mut self, value: Tone) -> Self {{ self.tone = Some(value); self }}\n\
         pub fn emphasis(mut self, value: Emphasis) -> Self {{ self.emphasis = Some(value); self }}\n\
         pub fn surface(mut self, value: SurfaceLevel) -> Self {{ self.surface = Some(value); self }}\n\
         pub fn animation(mut self, value: Animation) -> Self {{ self.animation = Some(value); self }}\n\
         pub fn visibility(mut self, value: Visibility) -> Self {{ self.visibility = Some(value); self }}\n"
    );
    for field in extra_fields {
        body.push_str(&format!(
            "    pub fn {field}(mut self, value: serde_json::Value) -> Self {{ self.{field} = Some(value); self }}\n",
        ));
    }
    if let Some(typed_fields) = typed_fields {
        for (field, ty) in typed_fields {
            body.push_str(&format!(
                "    pub fn {field}(mut self, value: {ty}) -> Self {{ self.{field} = Some(value); self }}\n",
            ));
        }
    }
    if has_children {
        body.push_str(
            "    pub fn children(mut self, value: Vec<Component>) -> Self { self.children = value; self }\n\
             pub fn child(mut self, value: impl Into<Component>) -> Self { self.children.push(value.into()); self }\n",
        );
    }
    body.push_str("}\n\n");
    body
}

fn impl_from_component(name: &str) -> String {
    format!(
        "impl From<{name}> for Component {{\n\
         fn from(value: {name}) -> Self {{ Component::{name}(value) }}\n\
         }}\n\n"
    )
}
