//! Generates SDUI primitive structs and the unified [`Component`] enum.

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let primitives_path =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
            .join("sdui_primitives.json");
    let primitives_json = fs::read_to_string(&primitives_path).expect("read sdui_primitives.json");
    let primitives: Vec<PrimitiveSpec> =
        serde_json::from_str(&primitives_json).expect("parse sdui_primitives.json");

    let mut used_types: BTreeSet<String> = BTreeSet::new();
    let mut uses_action = false;
    let mut uses_value = false;

    for primitive in &primitives {
        for ty in primitive.fields.values() {
            collect_type_deps(ty, &mut used_types, &mut uses_action, &mut uses_value);
        }
    }

    let mut generated = String::from("// @generated by build.rs — do not edit\n");
    if uses_action {
        generated.push_str("use super::action::Action;\n");
    }
    generated.push_str("use super::common::{Animation, Emphasis, SurfaceLevel, Tone, Visibility");
    for ty in &used_types {
        generated.push_str(", ");
        generated.push_str(ty);
    }
    generated.push_str("};\n");
    if uses_value {
        generated.push_str("use serde_json::Value;\n");
    }
    generated.push_str("use serde::{Deserialize, Serialize};\n\n");

    let mut enum_variants = String::new();
    let mut from_impls = String::new();
    let mut type_name_arms = String::new();
    let mut variant_name_arms = String::new();
    let mut child_node_arms = String::new();
    let mut type_names = String::new();
    let mut variant_names = String::new();

    for primitive in &primitives {
        let struct_name = &primitive.name;
        let serde_name = &primitive.serde_name;
        let has_children = primitive.has_children;
        let fields = &primitive.fields;

        generated.push_str(&format!(
            "/// SDUI primitive `{serde_name}` — see PORTAKI_PLATFORM.md §5.\n"
        ));
        generated.push_str("#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]\n");
        generated.push_str(&format!("pub struct {struct_name} {{\n"));
        generated.push_str(common_field_defs());
        for (field, ty) in fields {
            let rust_ty = rust_type(ty);
            generated.push_str(&format!(
                "    #[serde(skip_serializing_if = \"Option::is_none\")]\n\
                 pub {field}: Option<{rust_ty}>,\n",
            ));
        }
        if has_children {
            generated.push_str(
                "    #[serde(skip_serializing_if = \"Vec::is_empty\", default)]\n\
                 pub children: Vec<Component>,\n",
            );
        }
        generated.push_str("}\n\n");
        generated.push_str(&impl_builder(struct_name, has_children, fields));

        enum_variants.push_str(&format!(
            "    #[serde(rename = \"{serde_name}\")]\n    {struct_name}({struct_name}),\n"
        ));
        from_impls.push_str(&impl_from_component(struct_name));
        from_impls.push_str(&impl_sdui_primitive(struct_name, serde_name));
        type_name_arms.push_str(&format!(
            "            Component::{struct_name}(_) => \"{serde_name}\",\n"
        ));
        variant_name_arms.push_str(&format!(
            "            Component::{struct_name}(_) => \"{struct_name}\",\n"
        ));
        type_names.push_str(&format!("        \"{serde_name}\",\n"));
        variant_names.push_str(&format!("        \"{struct_name}\",\n"));
        if let Some(arm) = child_node_arm(struct_name, has_children, fields) {
            child_node_arms.push_str(&arm);
        }
    }

    generated.push_str("/// Unified SDUI component tree node.\n");
    generated.push_str(
        "#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]\n\
         #[serde(tag = \"type\")]\n\
         pub enum Component {\n",
    );
    generated.push_str(&enum_variants);
    generated.push_str("}\n\n");
    generated.push_str(&from_impls);
    generated.push_str(&impl_component_tree(
        &type_names,
        &variant_names,
        &type_name_arms,
        &variant_name_arms,
        &child_node_arms,
    ));
    generated.push_str(
        "impl Default for Component {\n\
         fn default() -> Self {\n\
         Component::Stack(Stack::default())\n\
         }\n\
         }\n",
    );

    let dest = out_dir.join("generated_sdui.rs");
    fs::write(&dest, generated).expect("write generated_sdui.rs");
    println!("cargo:rerun-if-changed=sdui_primitives.json");
}

/// Les types de `sdui/common.rs` qui portent un nœud dans `content: Option<Box<Component>>`.
///
/// `build.rs` ne lit que le contrat JSON, qui nomme ces types sans les décrire : il ne peut pas
/// deviner qu'un `AccordionItem` contient un arbre. Le test `sdui_tree` relit `common.rs` et
/// échoue si un type y porte un `Component` sans figurer ici.
const NODE_ITEM_TYPES: [&str; 2] = ["AccordionItem", "TabItem"];

#[derive(serde::Deserialize)]
struct PrimitiveSpec {
    name: String,
    serde_name: String,
    has_children: bool,
    #[serde(default)]
    fields: BTreeMap<String, String>,
}

fn collect_type_deps(
    ty: &str,
    used: &mut BTreeSet<String>,
    uses_action: &mut bool,
    uses_value: &mut bool,
) {
    match ty {
        "String" | "bool" | "f64" | "u32" | "i64" => {}
        // `Component` est généré dans CE module : il est déjà en portée, pas à importer.
        "Component" => {}
        "Action" => *uses_action = true,
        "Value" => *uses_value = true,
        other if other.starts_with("Vec<") && other.ends_with('>') => {
            let inner = &other[4..other.len() - 1];
            collect_type_deps(inner, used, uses_action, uses_value);
        }
        other => {
            used.insert(other.to_string());
        }
    }
}

fn rust_type(ty: &str) -> String {
    match ty {
        "Value" => "Value".to_string(),
        // Un nœud imbriqué dans un primitif, qui est lui-même une variante de `Component` :
        // sans `Box`, le type aurait une taille infinie. `Vec<Component>` n'en a pas besoin.
        "Component" => "Box<Component>".to_string(),
        other => other.to_string(),
    }
}

fn common_field_defs() -> &'static str {
    "    #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub id: Option<String>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub tone: Option<Tone>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub emphasis: Option<Emphasis>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub surface: Option<SurfaceLevel>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub animation: Option<Animation>,\n\
     #[serde(skip_serializing_if = \"Option::is_none\")]\n\
     pub visibility: Option<Visibility>,\n"
}

fn builder_setter(field: &str, ty: &str) -> String {
    match ty {
        // Le champ est `Option<Box<Component>>`, mais l'appelant écrit `.left(Text::new()...)` :
        // c'est le setter qui emballe, pas lui.
        "Component" => format!(
            "    pub fn {field}(mut self, value: impl Into<Component>) -> Self {{\n\
             self.{field} = Some(Box::new(value.into()));\n\
             self\n\
             }}\n"
        ),
        "String" => format!(
            "    pub fn {field}(mut self, value: impl Into<String>) -> Self {{\n\
             self.{field} = Some(value.into());\n\
             self\n\
             }}\n"
        ),
        other => format!(
            "    pub fn {field}(mut self, value: {other}) -> Self {{\n\
             self.{field} = Some(value);\n\
             self\n\
             }}\n"
        ),
    }
}

fn impl_builder(name: &str, has_children: bool, fields: &BTreeMap<String, String>) -> String {
    let mut body = format!(
        "impl {name} {{\n\
         /// Creates an empty `{name}` primitive.\n\
         pub fn new() -> Self {{ Self::default() }}\n\
         pub fn id(mut self, value: impl Into<String>) -> Self {{ self.id = Some(value.into()); self }}\n\
         pub fn tone(mut self, value: Tone) -> Self {{ self.tone = Some(value); self }}\n\
         pub fn emphasis(mut self, value: Emphasis) -> Self {{ self.emphasis = Some(value); self }}\n\
         pub fn surface(mut self, value: SurfaceLevel) -> Self {{ self.surface = Some(value); self }}\n\
         pub fn animation(mut self, value: Animation) -> Self {{ self.animation = Some(value); self }}\n\
         pub fn visibility(mut self, value: Visibility) -> Self {{ self.visibility = Some(value); self }}\n"
    );
    for (field, ty) in fields {
        body.push_str(&builder_setter(field, ty));
    }
    if has_children {
        body.push_str(
            "    pub fn children(mut self, value: Vec<Component>) -> Self { self.children = value; self }\n\
             pub fn child(mut self, value: impl Into<Component>) -> Self { self.children.push(value.into()); self }\n",
        );
    }
    body.push_str("}\n\n");
    body
}

fn impl_sdui_primitive(name: &str, serde_name: &str) -> String {
    format!(
        "impl SduiPrimitive for {name} {{\n\
         const TYPE_NAME: &'static str = \"{serde_name}\";\n\
         fn from_component(node: &Component) -> Option<&Self> {{\n\
         match node {{ Component::{name}(inner) => Some(inner), _ => None }}\n\
         }}\n\
         }}\n\n"
    )
}

/// L'élément d'un champ `Vec<T>` ou `T`, tel que le contrat l'écrit.
fn element_type(ty: &str) -> (&str, bool) {
    match ty.strip_prefix("Vec<").and_then(|t| t.strip_suffix('>')) {
        Some(inner) => (inner, true),
        None => (ty, false),
    }
}

/// Le bras de `Component::child_nodes` d'un primitif, ou `None` s'il ne porte aucun nœud.
///
/// Trois sources, dans cet ordre : les champs typés `Component` ou `Vec<Component>`, le
/// `content` des éléments de [`NODE_ITEM_TYPES`] (champs dans l'ordre du contrat), puis
/// `children`.
fn child_node_arm(
    name: &str,
    has_children: bool,
    fields: &BTreeMap<String, String>,
) -> Option<String> {
    let mut body = String::new();
    for (field, ty) in fields {
        let (element, is_vec) = element_type(ty);
        let line = match (element, is_vec) {
            // `Component` seul devient `Box<Component>` (voir `rust_type`).
            ("Component", false) => {
                format!("if let Some(node) = inner.{field}.as_deref() {{ nodes.push(node); }}")
            }
            ("Component", true) => {
                format!("if let Some(items) = &inner.{field} {{ nodes.extend(items.iter()); }}")
            }
            (item, false) if NODE_ITEM_TYPES.contains(&item) => format!(
                "if let Some(node) = inner.{field}.as_ref().and_then(|i| i.content.as_deref()) \
                 {{ nodes.push(node); }}"
            ),
            (item, true) if NODE_ITEM_TYPES.contains(&item) => format!(
                "if let Some(items) = &inner.{field} {{ \
                 nodes.extend(items.iter().filter_map(|i| i.content.as_deref())); }}"
            ),
            _ => continue,
        };
        body.push_str("                ");
        body.push_str(&line);
        body.push('\n');
    }
    if has_children {
        body.push_str("                nodes.extend(inner.children.iter());\n");
    }
    if body.is_empty() {
        return None;
    }
    Some(format!(
        "            Component::{name}(inner) => {{\n{body}            }}\n"
    ))
}

fn impl_component_tree(
    type_names: &str,
    variant_names: &str,
    type_name_arms: &str,
    variant_name_arms: &str,
    child_node_arms: &str,
) -> String {
    let node_item_types = NODE_ITEM_TYPES
        .iter()
        .map(|ty| format!("\"{ty}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "impl Component {{\n\
         /// Every primitive `type` declared by the contract, in contract order.\n\
         pub const TYPE_NAMES: &'static [&'static str] = &[\n{type_names}    ];\n\n\
         /// Every Rust variant name, in contract order (same index as [`Self::TYPE_NAMES`]).\n\
         pub const VARIANT_NAMES: &'static [&'static str] = &[\n{variant_names}    ];\n\n\
         /// Wire name of this node: the `type` field of its JSON (`\"Surface\"` for\n\
         /// [`SurfacePrimitive`]).\n\
         pub fn type_name(&self) -> &'static str {{\n\
         match self {{\n{type_name_arms}        }}\n\
         }}\n\n\
         /// Rust variant name of this node (`\"SurfacePrimitive\"` for the `Surface` primitive).\n\
         pub fn variant_name(&self) -> &'static str {{\n\
         match self {{\n{variant_name_arms}        }}\n\
         }}\n\n\
         /// Direct child nodes, in order: fields holding a node (such as `Split::left`, or the\n\
         /// `content` of `Accordion` and `Tabs` items), then `children`.\n\
         ///\n\
         /// Generated from `sdui_primitives.json`, so every primitive able to hold a node is\n\
         /// covered.\n\
         pub fn child_nodes(&self) -> Vec<&Component> {{\n\
         let mut nodes: Vec<&Component> = Vec::new();\n\
         match self {{\n{child_node_arms}            _ => {{}}\n        }}\n\
         nodes\n\
         }}\n\
         }}\n\n\
         /// Types of `sdui/common.rs` whose `content` field holds a nested node.\n\
         #[doc(hidden)]\n\
         pub const NODE_ITEM_TYPES: &[&str] = &[{node_item_types}];\n"
    )
}

fn impl_from_component(name: &str) -> String {
    format!(
        "impl From<{name}> for Component {{\n\
         fn from(value: {name}) -> Self {{ Component::{name}(value) }}\n\
         }}\n\n"
    )
}
