import type { ColumnDef, ModuleSchemaDef, TableDef } from '@portaki/sdk'

import { sqlType } from './sql-type.js'

export type SchemaMigrationRevision = {
  readonly revision: string
  readonly sql: string
}

/**
 * Emits idempotent baseline SQL for the modules database (no FK to API core).
 */
export function generateSchemaMigrations(
  moduleId: string,
  schemaVersion: string,
  schema: ModuleSchemaDef,
): SchemaMigrationRevision[] {
  const revision = `generated_${sanitizeRevision(schemaVersion)}_baseline`
  const statements: string[] = [
    `-- Generated by @portaki/cli for module "${moduleId}" @ schema ${schemaVersion}`,
    '-- Modules DB only — property_id / tenant_id are logical refs to portaki-api core.',
    '',
  ]

  for (const table of schema.tables) {
    statements.push(...createTableStatements(table))
    statements.push('')
  }

  return [{ revision, sql: statements.join('\n').trim() + '\n' }]
}

function createTableStatements(table: TableDef): string[] {
  const lines: string[] = []
  lines.push(`CREATE TABLE IF NOT EXISTS ${table.tableName} (`)
  const columnLines = table.columns.map((c: ColumnDef) => `    ${c.sqlName} ${sqlType(c)}`)
  lines.push(columnLines.join(',\n'))
  lines.push(');')

  for (const idx of table.indexes) {
    const cols = idx.columns.map((c: string) => toSnakeCase(c)).join(', ')
    const unique = idx.unique ? 'UNIQUE ' : ''
    lines.push(
      `CREATE ${unique}INDEX IF NOT EXISTS ${table.tableName}_${idx.name}_idx ON ${table.tableName} (${cols});`,
    )
  }

  return lines
}

function sanitizeRevision(version: string): string {
  return version.replace(/[^a-zA-Z0-9._-]+/g, '_')
}

function toSnakeCase(value: string): string {
  return value
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
}
