//! CLI subcommands.

pub mod add;
pub mod build;
pub mod catalog;
pub mod check;
pub mod ci;
pub mod connectors;
pub mod dev;
pub mod docs;
pub mod doctor;
pub mod i18n;
pub mod init;
pub mod inspect;
pub mod link;
pub mod lint;
pub mod login;
pub mod logs;
pub mod permissions;
pub mod release;
pub mod release_notes;
pub mod reports;
pub mod sandbox;
pub mod sdk;
pub mod status;
pub mod test;
