//! CLI subcommands.

pub mod build;
pub mod catalog;
pub mod check;
pub mod ci;
pub mod connectors;
pub mod dev;
pub mod docs;
pub mod i18n;
pub mod init;
pub mod inspect;
pub mod link;
pub mod lint;
pub mod login;
pub mod logs;
pub mod permissions;
pub mod publish;
pub mod sdk;
pub mod test;
