//! Depth-first queries over rendered [`portaki_sdk::sdui::surface::Surface`] trees.
//!
//! [`SurfaceAssertions`] walks every node of a surface, for **every** primitive of the SDUI
//! contract: the tree walk ([`Component::child_nodes`]) and the typed matching
//! ([`SduiPrimitive`]) are generated by `portaki-sdk` from `sdui_primitives.json`, so a primitive
//! added to the contract is covered here without any change.
//!
//! Nodes are visited in pre-order (a node before its children, children in order). Child nodes
//! include `children`, single-node fields such as `Split::left`, and the `content` of `Accordion`
//! and `Tabs` items.
//!
//! # Replacing a hand-written `contains_component_type`
//!
//! Module tests used to carry their own walker:
//!
//! ```ignore
//! fn contains_component_type(surface: &Surface, type_name: &str) -> bool {
//!     fn walk(node: &Component, type_name: &str) -> bool {
//!         let matches = match node {
//!             Component::Card(_) if type_name == "Card" => true,
//!             // …one arm per primitive the module happens to use
//!             _ => false,
//!         };
//!         matches || child_components(node).into_iter().any(|c| walk(c, type_name))
//!     }
//!     walk(&surface.root, type_name)
//! }
//!
//! assert!(contains_component_type(&surface, "Card"));
//! ```
//!
//! Delete it (and `child_components`) and use [`SurfaceAssertions`]:
//!
//! ```
//! use portaki_sdk::sdui::primitives::{Button, Card, Form, Split, Stack, Text};
//! use portaki_sdk::sdui::surface::Surface;
//! use portaki_test_utils::SurfaceAssertions;
//!
//! let surface = Surface::new(
//!     Stack::new()
//!         .child(Card::new().title("Wi-Fi").child(Text::new().text("portaki-guest")))
//!         .child(Split::new().left(Form::new().child(Button::new()))),
//! );
//! let tree = SurfaceAssertions::new(&surface);
//!
//! // By wire name: a drop-in for `contains_component_type(&surface, "Card")`.
//! assert!(tree.contains_type("Card"));
//! assert!(tree.contains_type("Button")); // found through `Split::left`
//! assert!(!tree.contains_type("EmptyState"));
//! assert_eq!(tree.count_type("Text"), 1);
//! tree.assert_contains_type("Form");
//!
//! // By type, to inspect the primitive itself.
//! assert!(tree.contains_primitive::<Card>());
//! assert_eq!(tree.count::<Card>(), 1);
//! assert_eq!(tree.find::<Card>().and_then(|c| c.title).as_deref(), Some("Wi-Fi"));
//! tree.assert_contains::<Button>();
//! ```
//!
//! String queries panic on a name that is not a primitive of the contract, so a typo cannot turn
//! `assert!(!tree.contains_type("Emptystate"))` into a test that always passes.

use portaki_sdk::sdui::component::Component;
use portaki_sdk::sdui::primitives::SduiPrimitive;
use portaki_sdk::sdui::surface::Surface;

/// Borrowed wrapper for depth-first SDUI tree queries.
#[derive(Debug, Clone)]
pub struct SurfaceAssertions<'a> {
    surface: &'a Surface,
}

impl<'a> SurfaceAssertions<'a> {
    /// Creates assertions over `surface.root` and its descendants.
    pub fn new(surface: &'a Surface) -> Self {
        Self { surface }
    }

    /// Every node of the surface, root included, in pre-order.
    pub fn nodes(&self) -> Vec<&'a Component> {
        let mut nodes = Vec::new();
        let mut stack = vec![&self.surface.root];
        while let Some(node) = stack.pop() {
            nodes.push(node);
            stack.extend(node.child_nodes().into_iter().rev());
        }
        nodes
    }

    /// Returns `true` if any node has the given type name.
    ///
    /// `type_name` is the wire name (the JSON `type`, e.g. `"Card"`, `"Surface"`); the Rust
    /// variant name (`"SurfacePrimitive"`) is accepted too.
    ///
    /// # Panics
    ///
    /// When `type_name` is not a primitive of the SDUI contract.
    pub fn contains_type(&self, type_name: &str) -> bool {
        self.find_by_type(type_name).is_some()
    }

    /// Returns the first node (pre-order) with the given type name.
    ///
    /// # Panics
    ///
    /// When `type_name` is not a primitive of the SDUI contract.
    pub fn find_by_type(&self, type_name: &str) -> Option<&'a Component> {
        check_type_name(type_name);
        self.nodes()
            .into_iter()
            .find(|node| has_type(node, type_name))
    }

    /// Returns every node (pre-order) with the given type name.
    ///
    /// # Panics
    ///
    /// When `type_name` is not a primitive of the SDUI contract.
    pub fn find_all_by_type(&self, type_name: &str) -> Vec<&'a Component> {
        check_type_name(type_name);
        self.nodes()
            .into_iter()
            .filter(|node| has_type(node, type_name))
            .collect()
    }

    /// Counts the nodes with the given type name.
    ///
    /// # Panics
    ///
    /// When `type_name` is not a primitive of the SDUI contract.
    pub fn count_type(&self, type_name: &str) -> usize {
        self.find_all_by_type(type_name).len()
    }

    /// Panics, listing the types present, when no node has the given type name.
    pub fn assert_contains_type(&self, type_name: &str) {
        assert!(
            self.contains_type(type_name),
            "expected surface to contain {type_name}, found: {}",
            self.present_types()
        );
    }

    /// Returns `true` if any node matches primitive `T`.
    pub fn contains_primitive<T: PrimitiveTag>(&self) -> bool {
        self.find::<T>().is_some()
    }

    /// Returns the first pre-order match for primitive `T`, if any.
    pub fn find<T: PrimitiveTag>(&self) -> Option<T::Output> {
        self.nodes().into_iter().find_map(T::match_node)
    }

    /// Returns every pre-order match for primitive `T`.
    pub fn find_all<T: PrimitiveTag>(&self) -> Vec<T::Output> {
        self.nodes().into_iter().filter_map(T::match_node).collect()
    }

    /// Counts the nodes matching primitive `T`.
    pub fn count<T: PrimitiveTag>(&self) -> usize {
        self.find_all::<T>().len()
    }

    /// Panics with `T::NAME`, listing the types present, when no node matches primitive `T`.
    pub fn assert_contains<T: PrimitiveTag>(&self) {
        assert!(
            self.contains_primitive::<T>(),
            "expected surface to contain {}, found: {}",
            T::NAME,
            self.present_types()
        );
    }

    fn present_types(&self) -> String {
        let mut types: Vec<&str> = self.nodes().iter().map(|n| n.type_name()).collect();
        types.sort_unstable();
        types.dedup();
        types.join(", ")
    }
}

fn check_type_name(type_name: &str) {
    assert!(
        Component::TYPE_NAMES.contains(&type_name) || Component::VARIANT_NAMES.contains(&type_name),
        "`{type_name}` is not an SDUI primitive; known types: {}",
        Component::TYPE_NAMES.join(", ")
    );
}

fn has_type(node: &Component, type_name: &str) -> bool {
    node.type_name() == type_name || node.variant_name() == type_name
}

/// Associates a type with the [`Component`] nodes it matches, for [`SurfaceAssertions`] queries.
///
/// Implemented for every [`SduiPrimitive`] (every primitive struct of
/// [`portaki_sdk::sdui::primitives`]), with `Output` the primitive itself.
pub trait PrimitiveTag {
    /// Human-readable primitive name used in panic messages.
    const NAME: &'static str;
    /// Concrete value extracted when `match_node` succeeds.
    type Output: Clone;
    /// Attempts to downcast `node` to this primitive.
    fn match_node(node: &Component) -> Option<Self::Output>;
}

impl<T: SduiPrimitive> PrimitiveTag for T {
    const NAME: &'static str = T::TYPE_NAME;
    type Output = T;

    fn match_node(node: &Component) -> Option<Self::Output> {
        T::from_component(node).cloned()
    }
}

#[cfg(test)]
mod tests {
    use portaki_sdk::sdui::primitives::{
        Accordion, Button, Card, Component, Divider, Form, Page, Section, Split, Stack,
        SurfacePrimitive, Tabs, Text,
    };
    use portaki_sdk::sdui::surface::Surface;
    use portaki_sdk::sdui::{AccordionItem, TabItem};

    use super::SurfaceAssertions;

    /// Page > Section > Stack > Card > Form > Stack > Button, with a Text beside the Section
    /// and one inside the Form.
    fn deep_surface() -> Surface {
        Surface::new(
            Page::new().child(Text::new().text("0")).child(
                Section::new().child(
                    Stack::new().child(
                        Card::new().title("outer").child(
                            Form::new()
                                .child(Text::new().text("1"))
                                .child(Stack::new().child(Button::new().label("deep"))),
                        ),
                    ),
                ),
            ),
        )
    }

    #[test]
    fn finds_a_deeply_nested_primitive() {
        let surface = deep_surface();
        let tree = SurfaceAssertions::new(&surface);

        assert!(tree.contains_type("Button"));
        assert!(tree.contains_primitive::<Button>());
        assert_eq!(
            tree.find::<Button>().and_then(|b| b.label).as_deref(),
            Some("deep")
        );
        assert_eq!(tree.count_type("Stack"), 2);
        assert_eq!(tree.count::<Text>(), 2);
        tree.assert_contains_type("Form");
        tree.assert_contains::<Button>();
    }

    #[test]
    fn walks_in_pre_order() {
        let surface = deep_surface();
        let tree = SurfaceAssertions::new(&surface);

        let texts: Vec<Option<String>> = tree
            .find_all::<Text>()
            .into_iter()
            .map(|t| t.text)
            .collect();
        assert_eq!(texts, [Some("0".to_string()), Some("1".to_string())]);

        let types: Vec<&str> = tree.nodes().iter().map(|n| n.type_name()).collect();
        assert_eq!(
            types,
            ["Page", "Text", "Section", "Stack", "Card", "Form", "Text", "Stack", "Button"]
        );
    }

    #[test]
    fn finds_primitives_behind_single_node_fields() {
        let tabs = Tabs::new().tabs(vec![TabItem {
            content: Some(Box::new(Divider::new().into())),
            ..TabItem::default()
        }]);
        let surface = Surface::new(Split::new().left(Card::new().child(Button::new())).right(
            Accordion::new().items(vec![AccordionItem {
                title: None,
                content: Some(Box::new(tabs.into())),
            }]),
        ));
        let tree = SurfaceAssertions::new(&surface);

        assert!(tree.contains_type("Card"));
        assert!(tree.contains_type("Button"));
        assert!(tree.contains_type("Tabs"));
        assert!(tree.contains_primitive::<Divider>());
    }

    #[test]
    fn a_leaf_root_is_its_only_node() {
        let surface = Surface::new(Text::new().text("seul"));
        let tree = SurfaceAssertions::new(&surface);

        assert_eq!(tree.nodes().len(), 1);
        assert!(tree.contains_type("Text"));
        assert_eq!(tree.count::<Text>(), 1);
        assert!(!tree.contains_type("Card"));
    }

    #[test]
    fn reports_absence() {
        let surface = deep_surface();
        let tree = SurfaceAssertions::new(&surface);

        assert!(!tree.contains_type("EmptyState"));
        assert!(tree.find_by_type("QRCode").is_none());
        assert!(tree.find_all_by_type("Map").is_empty());
        assert_eq!(tree.count_type("Image"), 0);
        assert!(tree.find::<Divider>().is_none());
        assert_eq!(tree.count::<Split>(), 0);
    }

    #[test]
    fn matches_the_surface_primitive_by_wire_and_variant_name() {
        let surface = Surface::new(SurfacePrimitive::new().child(Text::new()));
        let tree = SurfaceAssertions::new(&surface);

        assert!(tree.contains_type("Surface"));
        assert!(tree.contains_type("SurfacePrimitive"));
        assert!(tree.contains_primitive::<SurfacePrimitive>());
    }

    /// Every primitive of the contract, nested two levels down, is found by its name.
    #[test]
    fn every_contract_primitive_is_found_by_name() {
        for name in Component::TYPE_NAMES {
            let node: Component = serde_json::from_value(serde_json::json!({ "type": name }))
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            let surface = Surface::new(Stack::new().child(Card::new().child(node)));
            assert!(
                SurfaceAssertions::new(&surface).contains_type(name),
                "{name}"
            );
        }
    }

    #[test]
    #[should_panic(expected = "`Emptystate` is not an SDUI primitive")]
    fn an_unknown_type_name_panics() {
        let surface = deep_surface();
        SurfaceAssertions::new(&surface).contains_type("Emptystate");
    }

    #[test]
    #[should_panic(
        expected = "expected surface to contain Divider, found: Button, Card, Form, Page"
    )]
    fn a_failed_assertion_lists_the_types_present() {
        let surface = deep_surface();
        SurfaceAssertions::new(&surface).assert_contains::<Divider>();
    }
}
