//! Typed entity repository — SQL generated by the gateway, not module authors.
//!
//! Entities declared with `#[entity(...)]` map to isolated module schemas in Atlas.
//! Use [`typed::Query`] builders and [`typed::find`] / [`typed::create`] — never
//! embed SQL strings or access tables outside your module namespace.
//!
//! ## Contract
//!
//! - Entity type `E` resolves to the Rust struct name (e.g. `Poi` → `"Poi"`).
//! - [`typed::Page`] returns items plus an optional total count for pagination UI.
//! - Filters serialize to gateway Criteria — supported ops: eq, gte, in, spatial near.
//!
//! ## What modules must not assume
//!
//! - [`typed::create`] is an **upsert on primary key** at runtime (`INSERT … ON CONFLICT (id)
//!   DO UPDATE`). Prefer `create` for save/replace paths — do not delete-then-create.
//! - There is no separate partial-update API — use [`typed::create`] for upserts.
//! - Cross-module joins are unsupported — denormalize or use queries/commands.
//!
//! # Examples
//!
//! ```ignore
//! use portaki_sdk::prelude::*;
//! use portaki_sdk::host::repo::{self, eq, Direction};
//!
//! #[entity(schema_version = 1)]
//! struct Poi { id: uuid::Uuid, title: String }
//!
//! fn list_pois() -> Result<Vec<Poi>> {
//!     let page = repo::find::<Poi, Poi>(
//!         repo::Query::new().r#where(eq("title", "Beach")).limit(20),
//!     )?;
//!     Ok(page.items)
//! }
//! ```

#![allow(dead_code)]

use serde::{de::DeserializeOwned, Deserialize, Serialize};
use uuid::Uuid;

use crate::error::{PortakiError, Result};

/// Sort direction for repository queries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum Direction {
    /// Ascending order.
    Asc,
    /// Descending order.
    Desc,
}

/// Paginated query result envelope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Page<T> {
    /// Matching rows for the current page.
    pub items: Vec<T>,
    /// Total row count when the gateway computed it (may be `None` for large sets).
    pub total: Option<u64>,
}

/// Fluent, type-tagged query builder translated to gateway SQL.
#[derive(Debug, Clone, Serialize)]
pub struct Query<E> {
    filters: Vec<Filter>,
    order: Option<(String, Direction)>,
    limit: Option<u32>,
    _entity: std::marker::PhantomData<E>,
}

#[derive(Debug, Clone, Serialize)]
enum Filter {
    Eq(String, serde_json::Value),
    Gte(String, serde_json::Value),
    In(String, Vec<serde_json::Value>),
    SpatialNear {
        lat: f64,
        lng: f64,
        radius_meters: f64,
    },
}

impl<E> Default for Query<E> {
    fn default() -> Self {
        Self::new()
    }
}

impl<E> Query<E> {
    /// Starts a new query.
    pub fn new() -> Self {
        Self {
            filters: Vec::new(),
            order: None,
            limit: None,
            _entity: std::marker::PhantomData,
        }
    }

    /// Adds an equality filter.
    pub fn r#where(mut self, filter: FilterExpr) -> Self {
        match filter {
            FilterExpr::Eq(field, value) => self.filters.push(Filter::Eq(field, value)),
            FilterExpr::Gte(field, value) => self.filters.push(Filter::Gte(field, value)),
        }
        self
    }

    /// Adds an `IN` filter.
    pub fn where_in(mut self, field: impl Into<String>, values: Vec<serde_json::Value>) -> Self {
        self.filters.push(Filter::In(field.into(), values));
        self
    }

    /// Adds a spatial near filter.
    pub fn spatial(mut self, spec: SpatialExpr) -> Self {
        match spec {
            SpatialExpr::Near {
                lat,
                lng,
                radius_meters,
            } => {
                self.filters.push(Filter::SpatialNear {
                    lat,
                    lng,
                    radius_meters,
                });
            }
        }
        self
    }

    /// Orders results.
    pub fn order_by(mut self, field: impl Into<String>, direction: Direction) -> Self {
        self.order = Some((field.into(), direction));
        self
    }

    /// Limits page size.
    pub fn limit(mut self, limit: u32) -> Self {
        self.limit = Some(limit);
        self
    }

    /// Clears any page limit (used by [`count`]).
    fn without_limit(mut self) -> Self {
        self.limit = None;
        self
    }
}

/// Equality / comparison filter helpers.
pub enum FilterExpr {
    /// `field = value`
    Eq(String, serde_json::Value),
    /// `field >= value`
    Gte(String, serde_json::Value),
}

/// Builds `field = value`.
pub fn eq(field: impl Into<String>, value: impl Serialize) -> FilterExpr {
    FilterExpr::Eq(
        field.into(),
        serde_json::to_value(value).unwrap_or(serde_json::Value::Null),
    )
}

/// Builds `field >= value`.
pub fn gte(field: impl Into<String>, value: impl Serialize) -> FilterExpr {
    FilterExpr::Gte(
        field.into(),
        serde_json::to_value(value).unwrap_or(serde_json::Value::Null),
    )
}

/// Spatial helpers.
pub enum SpatialExpr {
    /// Points within `radius_meters` of (`lat`, `lng`).
    Near {
        /// Latitude.
        lat: f64,
        /// Longitude.
        lng: f64,
        /// Radius in meters.
        radius_meters: f64,
    },
}

/// Builds a near filter.
pub fn near(lat: f64, lng: f64, radius_meters: f64) -> SpatialExpr {
    SpatialExpr::Near {
        lat,
        lng,
        radius_meters,
    }
}

/// Repository namespace marker for entity type `E`.
///
/// Prefer free functions in [`typed`] (`repo::find`, `repo::create`) — this struct
/// exists for API symmetry with early platform examples.
pub struct Repo<E> {
    _entity: std::marker::PhantomData<E>,
}

impl<E> Repo<E> {
    /// Typed repository entry point.
    pub fn new() -> Self {
        Self {
            _entity: std::marker::PhantomData,
        }
    }
}

impl<E> Default for Repo<E> {
    fn default() -> Self {
        Self::new()
    }
}

/// Creates a row in the module schema and returns the persisted entity.
///
/// At runtime this is an upsert on the primary key (`id`): re-calling create with the same
/// `id` updates non-key columns. Prefer this over delete-then-create.
pub fn create<E, Create, Entity>(data: Create) -> Result<Entity>
where
    Entity: DeserializeOwned,
    Create: Serialize,
{
    let entity_name = entity_type_name::<E>();
    let host = crate::host::runtime::backend()?;
    let entity_json = serde_json::to_string(&data)?;
    let response_json = host.repo_create(entity_name, &entity_json)?;
    serde_json::from_str(&response_json).map_err(|e| PortakiError::Storage(e.to_string()))
}

/// Deletes a row by id.
pub fn delete<E>(id: Uuid) -> Result<bool> {
    let entity_name = entity_type_name::<E>();
    crate::host::runtime::backend()?.repo_delete(entity_name, &id.to_string())
}

/// Finds a row by id via [`find`] with an equality filter on `id`.
pub fn find_by_id<E, Entity>(id: Uuid) -> Result<Option<Entity>>
where
    Entity: DeserializeOwned,
{
    let page = find::<E, Entity>(Query::new().r#where(eq("id", id)).limit(1))?;
    Ok(page.items.into_iter().next())
}

/// Runs a typed query.
pub fn find<E, Entity>(query: Query<E>) -> Result<Page<Entity>>
where
    Entity: DeserializeOwned,
{
    let entity_name = entity_type_name::<E>();
    let host = crate::host::runtime::backend()?;
    let query_json = serde_json::to_string(&query)?;
    let response_json = host.repo_find(entity_name, &query_json)?;
    serde_json::from_str(&response_json).map_err(|e| PortakiError::Storage(e.to_string()))
}

fn entity_type_name<E>() -> &'static str {
    let full = std::any::type_name::<E>();
    full.rsplit("::").next().unwrap_or(full)
}

/// Counts rows matching a query (uses gateway `Page.total`, without a page limit).
pub fn count<E>(query: Query<E>) -> Result<u64> {
    let page: Page<serde_json::Value> = find(query.without_limit())?;
    page.total.ok_or_else(|| {
        PortakiError::Storage("repository count requires gateway total — none returned".into())
    })
}

/// Repository free functions and types — primary module authoring API.
pub mod typed {
    pub use super::{count, create, delete, find, find_by_id, Direction, Page, Query, Repo};
}

/// Returns a [`Repo`] marker for entity `E` (alias for [`typed::Repo::new`]).
pub fn repo<E>() -> Repo<E> {
    Repo::new()
}
